import img from ".//images/hero.jpg"

export const NavInfo = [
    {
        title: 'Home',
        link: '',
    },
    {
        title: 'Services',
        link: 'services',
        sublinks: [
            {
                title: 'CI/CD Automation',
                link: 'cicd-automation',
            },
            {
                title: 'DevSecOps',
                link: '',
            },
            {
                title: '24X7 Server Monitoring and Support',
                link: '',
            },
            {
                title: 'Cloud Migration',
                link: '',
            },
            {
                title: 'Devops & CICD',
                link: '',
            },
            {
                title: 'Fault-tolerant Infrastructure',
                link: '',
            },
            {
                title: 'Load and Stress Testing',
                link: '',
            },
            {
                title: 'App Modernization',
                link: '',
            },
            {
                title: 'Cloud and Devops Upskilling',
                link: '',
            },
        ]
    },
   
    {
        title: 'Trainings',
        link: 'trainings',        
    },
    {
        title: 'Contact Us',
        link: 'contact',
    },
]

export const servicesOverview = [
    {
        img: img,
        title: 'CI/CD AUTOMATION',
        desc: 'Enabling app deployment and management like never before.'
    },
    {
        img: img,
        title: 'DEVSECOPS INTEGRATED ',
        desc: 'Automation that has multi-layered security integrated.'
    },
    {
        img: img,
        title: '24X7 CLOUD SUPPORT',
        desc: 'Our cloud experts are available around the clock to assist you.'
    },

]


export const ServicesList = [
    {
        img: img,
        title: 'CLOUD MIGRATION',
        desc: "In today's rapidly evolving digital landscape, staying ahead means adapting to new paradigms swiftly and strategically. As you navigate the everchanging terrain of technology, We urge you to consider the immense benefits of migrating your workload from on-premise infrastructure to the cloud."
    },
    {
        img: img,
        title: 'DEVOPS $ CI/CD',
        desc: 'We help companies to implement the best DevOps practices and CI/CD automation methods in order to boost up the development process production and improve fault tolerance of services in production.'
    },
    {
        img: img,
        title: 'AULT-TOLERANT INFRASTRUCTURE',
        desc: 'Your project will be extremely stable and resistant to the failure of multiple servers. Even the fall of a meteorite on the data center will not make you worry at all.'
    },
    {
        img: img,
        title: 'STRESS & LOAD TESTING',
        desc: "We’ll show and tell you what your project is capable of! With the help of specialized tools we load the site this way, it imitates the behavior of real users, and observe how the system works in such conditions, where it can bug or fail, under what kind of load a failure might occur. We analyze data and makeour professional recommendations."
    },
    {
        img: img,
        title: '24X7 SERVER MONITORING & SUPPORT',
        desc: "24/7 Support over 1000 servers and 300 webprojects: from small corporate sites to major online stores, media sites and complex microservices projects. Do you want to be online 24/7 and sleep well? You’re at the right place!"
    },
]



export const AvailableCourses = [
    "Dev Ops",
    "DevOps & Cloud Computing",
    "Frontend Engineering",
    "Backend Engineering",
    "Fullstack Engineering"
]


export const countries = [
    { country: "Afghanistan", flag: "fi fi-af" },
    { country: "Albania", flag: "fi fi-al" },
    { country: "Algeria", flag: "fi fi-dz" },
    { country: "Andorra", flag: "fi fi-ad" },
    { country: "Angola", flag: "fi fi-ao" },
    { country: "Argentina", flag: "fi fi-ar" },
    { country: "Armenia", flag: "fi fi-am" },
    { country: "Australia", flag: "fi fi-au" },
    { country: "Austria", flag: "fi fi-at" },
    { country: "Azerbaijan", flag: "fi fi-az" },
    { country: "Bahamas", flag: "fi fi-bs" },
    { country: "Bahrain", flag: "fi fi-bh" },
    { country: "Bangladesh", flag: "fi fi-bd" },
    { country: "Barbados", flag: "fi fi-bb" },
    { country: "Belarus", flag: "fi fi-by" },
    { country: "Belgium", flag: "fi fi-be" },
    { country: "Belize", flag: "fi fi-bz" },
    { country: "Benin", flag: "fi fi-bj" },
    { country: "Bhutan", flag: "fi fi-bt" },
    { country: "Bolivia", flag: "fi fi-bo" },
    { country: "Botswana", flag: "fi fi-bw" },
    { country: "Brazil", flag: "fi fi-br" },
    { country: "Brunei", flag: "fi fi-bn" },
    { country: "Bulgaria", flag: "fi fi-bg" },
    { country: "Burkina", flag: "fi fi-bf" },
    { country: "Burundi", flag: "fi fi-bi" },
    { country: "Cambodia", flag: "fi fi-kh" },
    { country: "Cameroon", flag: "fi fi-cm" },
    { country: "Canada", flag: "fi fi-ca" },
    { country: "Cape Verde", flag: "fi fi-cv" },
    { country: "Chad", flag: "fi fi-td" },
    { country: "Chile", flag: "fi fi-cl" },
    { country: "China", flag: "fi fi-cn" },
    { country: "Colombia", flag: "fi fi-co" },
    { country: "Comoros", flag: "fi fi-km" },
    { country: "Costa Rica", flag: "fi fi-cr" },
    { country: "Croatia", flag: "fi fi-hr" },
    { country: "Cuba", flag: "fi fi-cu" },
    { country: "Cyprus", flag: "fi fi-cy" },
    { country: "Czech Republic", flag: "fi fi-cz" },
    { country: "Denmark", flag: "fi fi-dk" },
    { country: "Djibouti", flag: "fi fi-dj" },
    { country: "Dominica", flag: "fi fi-dm" },
    { country: "Dominican Republic", flag: "fi fi-do" },
    { country: "Ecuador", flag: "fi fi-ec" },
    { country: "Egypt", flag: "fi fi-eg" },
    { country: "El Salvador", flag: "fi fi-sv" },
    { country: "Equatorial Guinea", flag: "fi fi-gq" },
    { country: "Eritrea", flag: "fi fi-er" },
    { country: "Estonia", flag: "fi fi-ee" },
    { country: "Ethiopia", flag: "fi fi-et" },
    { country: "Fiji", flag: "fi fi-fj" },
    { country: "Finland", flag: "fi fi-fi" },
    { country: "France", flag: "fi fi-fr" },
    { country: "Gabon", flag: "fi fi-ga" },
    { country: "Gambia", flag: "fi fi-gm" },
    { country: "Georgia", flag: "fi fi-ge" },
    { country: "Germany", flag: "fi fi-de" },
    { country: "Ghana", flag: "fi fi-gh" },
    { country: "Greece", flag: "fi fi-gr" },
    { country: "Grenada", flag: "fi fi-gd" },
    { country: "Guatemala", flag: "fi fi-gt" },
    { country: "Guinea", flag: "fi fi-gn" },
    { country: "Guinea-Bissau", flag: "fi fi-gw" },
    { country: "Guyana", flag: "fi fi-gy" },
    { country: "Haiti", flag: "fi fi-ht" },
    { country: "Honduras", flag: "fi fi-hn" },
    { country: "Hungary", flag: "fi fi-hu" },
    { country: "Iceland", flag: "fi fi-is" },
    { country: "India", flag: "fi fi-in" },
    { country: "Indonesia", flag: "fi fi-id" },
    { country: "Iran", flag: "fi fi-ir" },
    { country: "Iraq", flag: "fi fi-iq" },
    { country: "Ireland", flag: "fi fi-ie" },
    { country: "Israel", flag: "fi fi-il" },
    { country: "Italy", flag: "fi fi-it" },
    { country: "Ivory Coast", flag: "fi fi-ci" },
    { country: "Jamaica", flag: "fi fi-jm" },
    { country: "Japan", flag: "fi fi-jp" },
    { country: "Jordan", flag: "fi fi-jo" },
    { country: "Kazakhstan", flag: "fi fi-kz" },
    { country: "Kenya", flag: "fi fi-ke" },
    { country: "Kiribati", flag: "fi fi-ki" },
    { country: "Kuwait", flag: "fi fi-kw" },
    { country: "Kyrgyzstan", flag: "fi fi-kg" },
    { country: "Laos", flag: "fi fi-la" },
    { country: "Latvia", flag: "fi fi-lv" },
    { country: "Lebanon", flag: "fi fi-lb" },
    { country: "Lesotho", flag: "fi fi-ls" },
    { country: "Liberia", flag: "fi fi-lr" },
    { country: "Libya", flag: "fi fi-ly" },
    { country: "Liechtenstein", flag: "fi fi-li" },
    { country: "Lithuania", flag: "fi fi-lt" },
    { country: "Luxembourg", flag: "fi fi-lu" },
    { country: "Macedonia", flag: "fi fi-mk" },
    { country: "Madagascar", flag: "fi fi-mg" },
    { country: "Malawi", flag: "fi fi-mw" },
    { country: "Malaysia", flag: "fi fi-my" },
    { country: "Maldives", flag: "fi fi-mv" },
    { country: "Mali", flag: "fi fi-ml" },
    { country: "Malta", flag: "fi fi-mt" },
    { country: "Marshall Islands", flag: "fi fi-mh" },
    { country: "Mauritania", flag: "fi fi-mr" },
    { country: "Mauritius", flag: "fi fi-mu" },
    { country: "Mexico", flag: "fi fi-mx" },
    { country: "Micronesia", flag: "fi fi-fm" },
    { country: "Moldova", flag: "fi fi-md" },
    { country: "Monaco", flag: "fi fi-mc" },
    { country: "Mongolia", flag: "fi fi-mn" },
    { country: "Montenegro", flag: "fi fi-me" },
    { country: "Morocco", flag: "fi fi-ma" },
    { country: "Mozambique", flag: "fi fi-mz" },
    { country: "Myanmar", flag: "fi fi-mm" },
    { country: "Namibia", flag: "fi fi-na" },
    { country: "Nauru", flag: "fi fi-nr" },
    { country: "Nepal", flag: "fi fi-np" },
    { country: "Netherlands", flag: "fi fi-nl" },
    { country: "New Zealand", flag: "fi fi-nz" },
    { country: "Nicaragua", flag: "fi fi-ni" },
    { country: "Niger", flag: "fi fi-ne" },
    { country: "Nigeria", flag: "fi fi-ng" },
    { country: "North Korea", flag: "fi fi-kp" },
    { country: "Norway", flag: "fi fi-no" },
    { country: "Pakistan", flag: "fi fi-pk" },
    { country: "Palau", flag: "fi fi-pw" },
    { country: "Panama", flag: "fi fi-pa" },
    { country: "Papua New Guinea", flag: "fi fi-pg" },
    { country: "Paraguay", flag: "fi fi-py" },
    { country: "Peru", flag: "fi fi-pe" },
    { country: "Philippines", flag: "fi fi-ph" },
    { country: "Poland", flag: "fi fi-pl" },
    { country: "Portugal", flag: "fi fi-pt" },
    { country: "Romania", flag: "fi fi-ro" },
    { country: "Russia", flag: "fi fi-ru" },
    { country: "Rwanda", flag: "fi fi-rw" },
    { country: "Saint Kitts and Nevis", flag: "fi fi-kn" },
    { country: "Saint Lucia", flag: "fi fi-lc" },
    { country: "Saint Vincent and the Grenadines", flag: "fi fi-vc" },
    { country: "Samoa", flag: "fi fi-ws" },
    { country: "San Marino", flag: "fi fi-sm" },
    { country: "Sao Tome and Principe", flag: "fi fi-st" },
    { country: "Saudi Arabia", flag: "fi fi-sa" },
    { country: "Senegal", flag: "fi fi-sn" },
    { country: "Serbia", flag: "fi fi-rs" },
    { country: "Seychelles", flag: "fi fi-sc" },
    { country: "Sierra Leone", flag: "fi fi-sl" },
    { country: "Singapore", flag: "fi fi-sg" },
    { country: "Slovakia", flag: "fi fi-sk" },
    { country: "Solomon Islands", flag: "fi fi-sb" },
    { country: "Somalia", flag: "fi fi-so" },
    { country: "South Africa", flag: "fi fi-za" },
    { country: "South Korea", flag: "fi fi-kr" },
    { country: "South Sudan", flag: "fi fi-ss" },
    { country: "Spain", flag: "fi fi-es" },
    { country: "Sri Lanka", flag: "fi fi-lk" },
    { country: "Sudan", flag: "fi fi-sd" },
    { country: "Suriname", flag: "fi fi-sr" },
    { country: "Swaziland", flag: "fi fi-sz" },
    { country: "Sweden", flag: "fi fi-se" },
    { country: "Switzerland", flag: "fi fi-ch" },
    { country: "Syria", flag: "fi fi-sy" },
    { country: "Taiwan", flag: "fi fi-tw" },
    { country: "Tajikistan", flag: "fi fi-tj" },
    { country: "Tanzania", flag: "fi fi-tz" },
    { country: "Thailand", flag: "fi fi-th" },
    { country: "Togo", flag: "fi fi-tg" },
    { country: "Tonga", flag: "fi fi-to" },
    { country: "Trinidad and Tobago", flag: "fi fi-tt" },
    { country: "Tunisia", flag: "fi fi-tn" },
    { country: "Turkey", flag: "fi fi-tr" },
    { country: "Turkmenistan", flag: "fi fi-tm" },
    { country: "Tuvalu", flag: "fi fi-tv" },
    { country: "Uganda", flag: "fi fi-ug" },
    { country: "Ukraine", flag: "fi fi-ua" },
    { country: "United Arab Emirates", flag: "fi fi-ae" },
    { country: "United Kingdom", flag: "fi fi-gb" },
    { country: "United States", flag: "fi fi-us" },
    { country: "Uruguay", flag: "fi fi-uy" },
    { country: "Uzbekistan", flag: "fi fi-uz" },
    { country: "Vanuatu", flag: "fi fi-vu" },
    { country: "Vatican City", flag: "fi fi-va" },
    { country: "Venezuela", flag: "fi fi-ve" },
    { country: "Vietnam", flag: "fi fi-vn" },
    { country: "Yemen", flag: "fi fi-ye" },
    { country: "Zambia", flag: "fi fi-zm" },
    { country: "Zimbabwe", flag: "fi fi-zw" }
];


export const ButtonClass = "rounded-full px-6 py-3 min-w-[200px] font-bold uppercase"